In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [ ]:
def get_spam_number(x):
    if x == 'spam':
        return 1
    return 0

In [12]:
df.shape

(5572, 3)

In [7]:
df['spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [9]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size =0.2)

In [21]:
X_train.shape

(4457,)

In [22]:
X_test.shape

(1115,)

In [23]:
type(X_train)

pandas.core.series.Series

In [24]:
X_train[:4]

1973    Yes but can we meet in town cos will go to gep...
4867    Oh! Shit, I thought that was your trip! Looooo...
2788    Forgot it takes me 3 years to shower, sorry. W...
3078              There is no sense in my foot and penis.
Name: Message, dtype: object

In [25]:
type(y_train)

pandas.core.series.Series

In [26]:
y_train[:4]

1973    0
4867    0
2788    0
3078    0
Name: spam, dtype: int64

In [27]:
type(X_train.values)

numpy.ndarray

In [29]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7772 sparse matrix of type '<class 'numpy.int64'>'
	with 59400 stored elements in Compressed Sparse Row format>

In [31]:
X_train_cv.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [34]:
X_train_cv.shape

(4457, 7772)

In [48]:
v.get_feature_names_out()[755]

'ac'

In [40]:
v.vocabulary_

{'yes': 7716,
 'but': 1570,
 'can': 1624,
 'we': 7435,
 'meet': 4437,
 'in': 3657,
 'town': 7025,
 'cos': 2009,
 'will': 7542,
 'go': 3173,
 'to': 6957,
 'gep': 3125,
 'and': 941,
 'then': 6845,
 'home': 3492,
 'you': 7731,
 'could': 2021,
 'text': 6806,
 'at': 1100,
 'bus': 1563,
 'stop': 6509,
 'don': 2409,
 'worry': 7627,
 'll': 4175,
 'have': 3373,
 'finished': 2872,
 'by': 1585,
 'march': 4368,
 'ish': 3766,
 'oh': 4918,
 'shit': 6110,
 'thought': 6885,
 'that': 6829,
 'was': 7410,
 'your': 7737,
 'trip': 7063,
 'loooooool': 4217,
 'just': 3894,
 'makes': 4344,
 'so': 6300,
 'much': 4649,
 'more': 4598,
 'sense': 6030,
 'now': 4850,
 'grins': 3258,
 'the': 6833,
 'sofa': 6304,
 'reference': 5675,
 'sleep': 6232,
 'on': 4939,
 'couch': 2017,
 'link': 4145,
 'sent': 6034,
 'me': 4421,
 'wasn': 7412,
 'how': 3536,
 'went': 7482,
 'didn': 2302,
 'babe': 1174,
 'with': 7571,
 'for': 2949,
 'celebration': 1699,
 'rents': 5727,
 'forgot': 2959,
 'it': 3775,
 'takes': 6716,
 'years': 7707

In [41]:
X_train_np = X_train_cv.toarray()

In [43]:
X_train_np[:4]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [44]:
np.where(X_train_np[0]!=0)

(array([ 941, 1100, 1563, 1570, 1585, 1624, 2009, 2021, 2409, 2872, 3125,
        3173, 3373, 3492, 3657, 3766, 4175, 4368, 4437, 6509, 6806, 6845,
        6957, 7025, 7435, 7542, 7627, 7716, 7731], dtype=int64),)

In [46]:
X_train[:4][4867]

'Oh! Shit, I thought that was your trip! Loooooool ... That just makes SO much more sense now ... *grins* and the sofa reference was ... The "sleep on a couch" link you sent me ... Wasn\'t that how you went on your trip ? Oh ... And didn\'t your babe go with you for that celebration with your rents?'

In [47]:
X_train_np[0][755]

0

In [50]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [53]:
X_test_cv = v.transform(X_test)

In [54]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       960
           1       0.96      0.95      0.95       155

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [55]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

In [56]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [57]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [58]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       960
           1       0.96      0.95      0.95       155

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115

